sudo: required
dist: trusty

language: haxe

haxe:
  - "3.4.4"
  - "3.4.7"
  - "4.0.3"
  - "development"

matrix:
  allow_failures:
    - haxe: development

install:
  - yes | haxelib install all

script:
  - haxe test.hxml


deploy:
  - provider: script
    haxe: 3.4.7
    script: bash ./release_haxelib.sh $HAXELIB_PWD
    on:
      tags: true
